# Generated by Django 5.1.2 on 2024-10-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_baseuser_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='jogos/')),
                ('url_jogo', models.URLField()),
                ('categoria', models.CharField(choices=[('recentes', 'Recentes'), ('outros', 'Outros')], max_length=10)),
            ],
        ),
    ]
