# Generated by Django 5.1.2 on 2024-10-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0003_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
        ),
    ]
