# Generated by Django 5.1.2 on 2024-10-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0006_alter_baseuser_email_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='categoria',
            field=models.CharField(choices=[('recentes', 'Recentes'), ('outros', 'Outros')], default='outros', max_length=10),
        ),
    ]
