# Generated by Django 5.1.2 on 2024-12-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0010_offensiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='photo',
            field=models.ImageField(blank=True, default='jogos/static/img/user 5.svg', null=True, upload_to='media/'),
        ),
    ]
