# Generated by Django 5.1.2 on 2024-12-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0012_alter_baseuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='products/covers/%Y/%m/%d/'),
        ),
    ]
