# Generated by Django 5.1.2 on 2024-12-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jogos', '0014_alter_baseuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_baseuser_groups', related_query_name='custom_baseuser_group', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_baseuser_permissions', related_query_name='custom_baseuser_permission', to='auth.permission'),
        ),
    ]
